platform :ios, '12.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$RNFirebaseAnalyticsWithoutAdIdSupport = true # toggle this to true for the no-ad-tracking Analytics subspec




target 'ExampleApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  
  # Pods for WoocommerceV3
  pod 'GoogleSignIn', '~> 6.1.0'
  pod 'WebEngage'
  # pod 'WebEngage', '5.2.11' # added as a build fail happened in 6.0.0
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'


  target 'ExampleAppTests' do
    inherit! :complete
    # Pods for testing
  end
  
  target 'ContentExtension' do
    
    pod 'WebEngageAppEx/ContentExtension'
  end

  
  # ServiceExtension Target
  target 'NotificationService' do

    pod 'WebEngageBannerPush'
  end

  # ContentExtension Target
  target 'NotificationViewController' do

  pod 'WebEngageAppEx/ContentExtension'
  end

  
  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.174.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      end
    end
  end
end

