
platform :ios, '9.0'

target 'ExampleApp' do

  pod 'WebEngage'

  target 'ExampleApp-tvOSTests' do
    inherit! :search_paths
  end

  target 'ExampleAppTests' do
    inherit! :search_paths
  end

end
